### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by bradyrenting** [statamic/starter-kit-starters-creek#1]
There is no license to be found in this repository. Would love to see MIT or Unlicense :smile:

**Comment by binari** [comment]
+1

**Comment by jackmcdade** [comment]
As it also contains the full Statamic cms codebase, we can’t make it MIT.

**Comment by bradyrenting** [comment]
> As it also contains the full Statamic cms codebase, we can’t make it MIT.

What alternative do you have in mind?

**Comment by jackmcdade** [comment]
Got any suggestions?

**Comment by bradyrenting** [comment]
Not really to be honest

**Comment by jasonvarga** [comment]
`statamic/cms` is a dependency of this project, and not really part of the project. Would MIT still screw with that?

**Comment by bradyrenting** [comment]
> `statamic/cms` is a dependency of this project, and not really part of the project. Would MIT still screw with that?

No, MIT would not screw with this. GPL-3 however would.

**Comment by jasonvarga** [comment]
I think MIT is probably fine for the starter kits. You can do what you want with the app. The source of the cms is a different story, but would be covered by its own license.

i.e. `laravel/laravel` is MIT, but that doesn't mean every Composer dependency automatically becomes MIT too, right?
