### ISSUE TITLE
Cannot be installed with statamic 3.3.2+ (dependency)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/starter-kit-starters-creek#11]
Problem 1
    - Root composer.json requires statamic/ssg ^0.8.0 -> satisfiable by statamic/ssg[0.8.0].
    - statamic/ssg 0.8.0 requires statamic/cms ~3.1.7 || 3.2.* -> found statamic/cms[v3.1.7, ..., 3.2.x-dev] but it conflicts with your root composer.json require (3.3.*).
   
ssg has been bumped to 1.0.0

**Comment by jackmcdade** [comment]
Fixed!
