### ISSUE TITLE
"Incorrect value type" from Google Search Console

### ISSUE THREAD

**Issue by connor11528** [statamic/starter-kit-starters-creek#2]
Hi there, I deployed a site using Statamic and connected to Google Search Console. The search console flagged a parsing error saying "Incorrect value type" for  `"@type": blogPost,` that is in the [antlers layout](https://github.com/statamic/starter-kit-starters-creek/blob/22e6d459a71f4577f7a22f1c3e6acaea495e678b/resources/views/layout.antlers.html#L12). Is this a value that needs to be set in the config or do we need to change the type setting here when on the homepage?

<img width="1141" alt="Screen Shot 2020-10-22 at 7 44 07 AM" src="https://user-images.githubusercontent.com/3578908/96888904-f241f680-143a-11eb-870b-0223ffb5684b.png">

**Comment by jasonvarga** [comment]
I'm no expert here but my guess is that it's just missing quotes and should be `"blogPost"`.

@jackmcdade ?

**Comment by connor11528** [comment]
Or maybe need quotes with curly brackets if we do want to use a variable here? https://developers.google.com/search/docs/guides/generate-structured-data-with-javascript 

<img width="890" alt="Screen Shot 2020-12-10 at 6 58 06 AM" src="https://user-images.githubusercontent.com/3578908/101788614-28a00780-3ab5-11eb-8513-39988a906566.png">

**Comment by jasonvarga** [comment]
Is it supposed to be a variable?

**Comment by connor11528** [comment]
thank you @jackmcdade!
