### ISSUE TITLE
There are no commands defined in the "starter-kit" namespace. 

### ISSUE THREAD

**Issue by diskbuster** [statamic/starter-kit-starters-creek#7]
Hi,
when i install the kit I get:

`  There are no commands defined in the "starter-kit" namespace.  
                                                                 

In NewCommand.php line 348:
                                                                        
  There was a problem installing Statamic with the chosen starter kit! `

it also happens with other starter kits.

what can I do?

**Comment by jackmcdade** [comment]
You need to be running Statamic 3.2 :)
